function [...
    batWfun, ...
    batSfun...
    ] = grim(...
    params, ...
    batWfun, ...
    batSfun, ...
    foundF, ...
    totalF, ...
    i_bat, ...
    i_day...
    )

b = params(1);
d = params(2);
r = params(3);
h = params(4);
c = params(5);
maxW = params(6);
minW = params(7);
minSW = params(8);

% if other bat
if i_bat == 1
    otherbat = 2;
elseif i_bat == 2
    otherbat = 1;
else
    otherbat = 0;
end

if batWfun(:, i_day) >= minW   % if all bats are alive
    
    if any(batSfun(otherbat, :) == 1)
        
        [batWfun, ...
            batSfun] = ...
            greedy(...
            params, ...
            batWfun, ...
            batSfun, ...
            foundF, ...
            totalF, ...
            i_bat, ...
            i_day...
            );
        
    else
        
        [batWfun, ...
            batSfun] = ...
            share(...
            params, ...
            batWfun, ...
            batSfun, ...
            foundF, ...
            totalF, ...
            i_bat, ...
            i_day...
            );
        
    end
    
else
    
    [batWfun, ...
        batSfun] = ...
        greedy(...
        params, ...
        batWfun, ...
        batSfun, ...
        foundF, ...
        totalF, ...
        i_bat, ...
        i_day...
        );
end

end